### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by yangze0930** [RBirkeland/MVCNN-PyTorch#2]
Hi,
I find that the data you provided is different from the [original implementation](https://github.com/suhangpro/mvcnn), where they have only 3,983 object instances and your dataset contains 12,311 object instances. Could you please tell me where the differences come from. Thank you for your help.

**Comment by RBirkeland** [comment]
Hey, thanks for checking out the project!

I'm not 100% sure where the original dataset came from, but there exists a v1 and v2 of modelnet40 dataset, which you can find [here](http://maxwell.cs.umass.edu/mvcnn-data/). Where v2 is a lot bigger, so that might explain the difference. Or you can also use [BlenderPhong](https://github.com/WeiTang114/BlenderPhong) to create new views of the original modelnet dataset.

I hope that helps!

**Comment by yangze0930** [comment]
It seems v2 of modelnet40 contains 80 views for each object instance. However, modelnet40 v2 has the same size of object instances with modelnet40 v1, the only difference is that modelnet40 v2 contains more views for each object instance.
